### ISSUE TITLE
timestamps on athena.read_sql_query wrap around to give wrong value in pandas

### ISSUE THREAD

**Issue by isichei** [awslabs/aws-data-wrangler#592] opened 2021-03-09 18:35 UTC
**Describe the bug**

When reading timestamp values that are out of bounds for `Timestamp[ns]` the values just get wrapped around to different timestamps (as far as I can tell). This only seems to be a problem for when you set `ctas_approach=True` in the `athena.read_sql_query` function. If you set this to False it is read in correctly. So I guess there is a mismatch between how Athena writes the data to parquet and wrangler reads in the parquet file?

**To Reproduce**

Soz this is fairly long as tried to make something reproducible. If you already have tables that have columns with out of bounds timestamps (for ns) then you can skip to my `# post-setup` comment in the code.

```python
# Create a table with timestamps that are out of bounds Timestamp[ns]
import awswrangler as wr
import pandas as pd
import datetime

i = pd.Series([0,1,2])
d = pd.Series([datetime.date(1000, 1, 1), datetime.date(2020,1,1), datetime.date(3000, 1, 1)])
dt = pd.Series(["1000-01-01 00:00:00", "2020-01-01 00:00:00", "3000-01-01 00:00:00"])
df = pd.DataFrame({"i": i, "d":d, "dt": dt})

# Create the database
database = "isichei_test"
wr.catalog.create_database(database)
table_path = "<Wherever you wanna throw your data>" 
wr.s3.to_parquet(
    df=df,
    path=table_path,
    index=False,
    dataset=True,
    database=database,
    table='test_table',
    mode="overwrite",
    dtype={"i": "int", "d": "date", "dt": "string"} # cannot specify timestamp as wrangler errors out here (due to same pandas TS casting issues)
)

# post-setup
## If you have tables in parquet that are stored as Timestamp[s] then you can just query them (i.e. SELECT *) - this cast in the SQL query is just for this example. In reality we discovered this on querying one of our tables that are written to parquet using Spark.

df_ctas = wr.athena.read_sql_query("SELECT *, cast(dt as timestamp) AS dt_timestamp FROM isichei_test.test_table", database="isichei_test")

df_ctas.dt_timestamp
# returns: 2169-02-08 23:09:07.419103232, 2020-01-01 00:00:00.000000000, 1830-11-23 00:50:52.580896768
```

### Some further notes

In the example above if you set `ctas_approach = False` you will get an Pandas error due to trying to apply dt accessor in something that isn't a dt. However, on our tables where the data is written to parquet via other means (spark or pyarrow) and you just query those values with `ctas_approach=False` you do not get the timestamp wrapping error. If you need it, I can try and create a reproducible error that lets me write parquet files to S3 using arrow (or something) but this is hopefully enough?

For our etl pipelines we now use Arrow to read in data and then try to strictly convert the timestamps to pandas object arrays to avoid `Timestamp[ns]` issues. I don't know if you have an option in this function or package to do the same (/ point me in the direction to PR it)? I am not 100% sure if this is actually a pandas read in issue rather than something like a weird mismatch in the parquet metadata between the Athena engine and wrangler. Finally, dates are unaffected the resulting output for the `d` column was correct.

Also worth noting we are still using the Athena v1 engine.

env:
```
awswrangler         2.3.0
pandas              1.2.0
pyarrow             2.0.0
```

**Comment by jaidisido** [comment] 2021-03-20 18:35
Thank you for the detailed steps @isichei, it helped reproduce the problem. However, this is an arrow library issue.

The CTAS Athena query is dumping a parquet S3 object with the results. The object is then read as an [arrow parquet file](https://github.com/awslabs/aws-data-wrangler/blob/cf99eafb7b0f6a0a46a1c29357e1ed5d5a5a4680/awswrangler/s3/_read_parquet.py#L371) by the `wr.s3.read_parquet` method and converted to an Arrow table where the `dt_timestamp` column is inferred to be of Arrow type `timestamp[ns]`. But the dates you submitted are considered out of range timestamps in Arrow 2.0.0 and it returns those wrong values at the edge instead. From my little research, anything inside this range more or less:
```
dt = pd.Series(["1677-09-22 00:00:00", "2020-01-01 00:00:00", "2262-04-11 00:00:00"])
``` 
is fine, but anything outside and Arrow returns weird timestamps.

Here are some additional links on the same issue:
- https://issues.apache.org/jira/browse/ARROW-6779
- https://github.com/awslabs/aws-data-wrangler/issues/296

In regards to why you are not encountering the error when `ctas_approach=False`, that is because in that case the result of the Athena query is a [CSV file that we then read directly from S3](https://github.com/awslabs/aws-data-wrangler/blob/cf99eafb7b0f6a0a46a1c29357e1ed5d5a5a4680/awswrangler/athena/_read.py#L489) without going through Arrow.

**Comment by isichei** [comment] 2021-03-23 08:23
Hi @jaidisido,

Thanks for replying, that makes sense. I was wondering if this means that you are going to wait for the issue to be fixed on pyarrow side? Otherwise the "fix" on your side would be setting `timestamp_as_object=True` in this [function call](https://github.com/awslabs/aws-data-wrangler/blob/fc77f1dad44a1719499306412560a7363c7604ac/awswrangler/s3/_read_parquet.py#L251-L261). This then avoids the pandas timestamp[ns] issue.

Another option (to ensure backwards compatability) is to allow users to pass kwargs to this function call when using the athena module (or by adding the option to set this in the configs for `awswrangler`). If you think it is worth trying and have a preferred method happy to give it a go myself on a PR.

**Comment by jaidisido** [comment] 2021-03-23 17:36
The issue is that the timestamps get messed by pyarrow before they reach that `_arrowtable2df` method. As I mentioned the parquet file is first [read](https://github.com/awslabs/aws-data-wrangler/blob/cf99eafb7b0f6a0a46a1c29357e1ed5d5a5a4680/awswrangler/s3/_read_parquet.py#L376) ([docs](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetFile.html#pyarrow.parquet.ParquetFile.read)) into a pyarrow table. At this point, the timestamps are already converted and wrong. Enabling `timestamp_as_object=True` on the subsequent call would not help at that point. Not sure how to circumvent that...

**Comment by isichei** [comment] 2021-03-26 10:01
Apologies @jaidisido you're right. Looks like the issue is specifically how `pyarrow` deals with Parquet INT96 types. Athena writes parquet data using the version 1.0 of parquet which uses INT96 types for timestamps (deprecated in later Parquet versions ([source](https://arrow.apache.org/docs/python/parquet.html#storing-timestamps))).

 When arrow reads the parquet file with a physical type of INT96 it will always infer that this should be a `timestamp[ns]` arrow type and then the wrap around occurs on conversion to the arrow table this will still happen without error for pyarrow v2 and v3. Interestingly the example in [ARROW-6779](https://issues.apache.org/jira/browse/ARROW-6779) now throws an out of bounds error if ran in pyarrow v3.0.0.

As far as I can tell the conversion from parquet type to arrow type is in the Cython code for the Parquet reader in the pyarrow library and the conversion is not exposed to the python APIs in pyarrow so you can't set it yourself. I've been able to create a round trip example just using pyarrow so will raise a ticket with them when I get the chance. 

Thanks for your help!

**Comment by jaidisido** [comment] 2021-03-26 10:09
Thank you for the clear explanation @isichei, please keep us posted on the outcome of the Arrow issue. Closing for now but feel free to reopen in the future

**Comment by isichei** [comment] 2021-03-26 11:07
For reference: https://issues.apache.org/jira/browse/ARROW-12096

**Comment by isichei** [comment] 2021-09-13 13:45
@jaidisido can we re-open now?

I have applied a fix / workaround for PyArrow (in v5 release)

**Comment by jaidisido** [comment] 2021-09-13 15:57
Thanks @isichei, latest version of Wrangler (2.11.0) has a [dependency](https://github.com/awslabs/aws-data-wrangler/blob/main/pyproject.toml#L39) on Pyarrow 5. As long as your fix is included in there, you could test it using the latest version.

**Comment by z-arosio** [comment] 2021-09-16 08:54
Hi,

i've a `pandas `dataframe with i.e. a column of type:
`ANDATNAS         datetime64[ns]`

and I wrote the dataframe as parquet, using both the `pandas` and the `awswrangler` methods:

```
df.to_parquet(
     path='my_path',
     engine='pyarrow',
     partition_cols=['table_version', 'version'],
     compression='snappy'
     )
wr.s3.to_parquet(
    df=df,
    path='my_path',
    boto3_session=s3_session,
    dataset=True,
    partition_cols=['table_version', 'version']
)
```
with these versions:
```
pyarrow==5.0.0
pandas==1.2.4
awswrangler==2.11.0
```
Then, i've ispected the parquet content with `parquet-tools`.
In the parquet written by `pandas`:
```
############ Column(ANDATNAS) ############
name: ANDATNAS
path: ANDATNAS
max_definition_level: 1
max_repetition_level: 0
physical_type: INT64
logical_type: Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false)
converted_type (legacy): NONE
```
while in the parquet written by `awswrangler`:
```
############ Column(ANDATNAS) ############
name: ANDATNAS
path: ANDATNAS
max_definition_level: 1
max_repetition_level: 0
physical_type: INT96
logical_type: None
converted_type (legacy): NONE
```
I can't manage the `INT96` type for dates exceeding limits (i.e. 1900) with tools like Athena, Presto or Trino:
`Invalid timeOfDayNanos: -82800000000000
`
I think the `INT96 ` type is deprecated and I suppose the problem is not in the `pyarrow` library (I'm using the same version in both `pandas` and `awsgrangler`) but in the way `awswrangler` is using it.

Any suggestion to write the parquet file in the right format also with `awswrangler`?

Thanks!

**Comment by isichei** [comment] 2021-09-17 13:14
Hi @jaidisido I might have time to try and apply a fix next week

**Comment by kukushking** [comment] 2021-09-17 15:01
@z-arosio Checking, not entirely sure yet where the difference comes from...

**Comment by z-arosio** [comment] 2021-09-17 16:01
@kukushking Thank you very much!
How could I pass the `use_deprecated_int96_timestamps` parameter to the [awswrangler.s3.to_parquet](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html) method?

**Comment by kukushking** [comment] 2021-09-20 13:01
@z-arosio I have sent a PR above, once merged you can install development version via:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
And pass via `wr.s3.to_parquet(..., pyarrow_additional_kwargs={"use_deprecated_int96_timestamps"=False})`

**Comment by isichei** [comment] 2021-09-28 08:33
Is it planned to merge the PR #917? This won't fix this specific issue but the same approach needs to be taken.

1. Allow the parquet read function to take `pyarrow` specific arguments
2. Then use `coerce_int96_timestamp_unit` in the pyarrow reader to get around Athena using the deprecated INT96 format.

If #917 is going to be merged then I'll add the args to the reader using the same conventions as #917 to be consistent

**Comment by kukushking** [comment] 2021-09-29 10:35
@isichei Yep, #917 is merged. We can follow the same approach for `read_parquet` - happy to accept the contribution!

**Comment by isichei** [comment] 2021-09-29 13:06
I've created a PR to fix this but I can't quite see why it is failing. Atm `black` suggests changing one of the files but when I run the same command locally black says it is fine (`black --check awswrangler/s3/_read_parquet.py -t py38` (also true for py37))

**Comment by z-arosio** [comment] 2021-09-29 13:10
> 
> 
> @z-arosio I have sent a PR above, once merged you can install development version via:
> 
> ```
> pip uninstall awswrangler -y
> pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
> ```
> 
> And pass via `wr.s3.to_parquet(..., pyarrow_additional_kwargs={"use_deprecated_int96_timestamps"=False})`

Thanks! It works!

**Comment by jaidisido** [comment] 2021-10-05 16:37
> I've created a PR to fix this but I can't quite see why it is failing. Atm `black` suggests changing one of the files but when I run the same command locally black says it is fine (`black --check awswrangler/s3/_read_parquet.py -t py38` (also true for py37))

Thanks @isichei, I have fixed the `black` issue for you but there are now some issues raised with `pylint`. Could you please check these?

**Closed** 2021-10-12 14:48 UTC
Labels: bug
