### ISSUE TITLE
Unable to query layer in eu-west-1

### ISSUE THREAD

**Issue by jrnhofman** [awslabs/aws-data-wrangler#1374] opened 2022-06-03 14:04 UTC
I'm unable to query layer version for the aws-data-wrangler layer for python3.7. I'm authenticated with an account located in eu-west-1 and can query other public layer ARNs in the region just fine.

Input:
`
aws lambda get-layer-version-by-arn --arn 'arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python37:6'
`

Output:
An error occurred (AccessDeniedException) when calling the GetLayerVersionByArn operation: User: <MY_USER> is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python37:6 because no resource-based policy allows the lambda:GetLayerVersion action

**Comment by jaidisido** [comment] 2022-06-03 14:38
Duplicate of https://github.com/awslabs/aws-data-wrangler/issues/1357

**Closed** 2022-06-03 14:38 UTC
