### ISSUE TITLE
awswrangler / s3.read_parquet Getting wrong dates if year less than 1677  or greater than 2262 

### ISSUE THREAD

**Issue by ragurajesh** [awslabs/aws-data-wrangler#1153] opened 2022-02-02 02:54 UTC
Using the below code i am trying to read the parquet file from s3.

import awswrangler as wr

df1 = wr.s3.read_parquet("s3://XXXXXXXXXXX/32.parquet", safe=False)

Once after executing this code when i try to read the data frame for the specific date column, i could see wrong date on it.

i.e. parquet file on the date column as "1515-01-31T09:00:00.000Z", but the same column read as "2099-08-30 08:34:33.709551616"  in data frame.

**Comment by jaidisido** [comment] 2022-02-02 10:54
This could be a duplicate of #592 (fixed in #949). Could you try the same call but add:
```
df1 = wr.s3.read_parquet("s3://XXXXXXXXXXX/32.parquet", safe=False, pyarrow_additional_kwargs={"coerce_int96_timestamp_unit": "ms", "timestamp_as_object": True})
```

**Comment by ragurajesh** [comment] 2022-02-03 00:05
Awesome , Thanks you so much, dates are now appearing as expected in data frames. 

![Screen Shot 2022-02-03 at 10 54 06 am](https://user-images.githubusercontent.com/67565725/152258460-bcd4cbb5-285f-4dc9-8ead-6b4d594653bc.png)
)

**Comment by ragurajesh** [comment] 2022-02-03 00:22
My apologies for the confusion , just now i realise still there are some differnce in dates..

my parquet contains as below :"end_date": "1515-01-31T09:00:00.000Z"

Data frame reading it as "1515-02-10 09:00:00"

I am using the below code

df1 = wr.s3.read_parquet("s3://XXXXXXXXXXX/32.parquet", safe=False, pyarrow_additional_kwargs={"coerce_int96_timestamp_unit": "ms", "timestamp_as_object": True})

Please help me here... :-(

**Comment by ragurajesh** [comment] 2022-02-07 03:36
Hello @jaidisido

did you had chance to check on this issue ?

**Comment by jaidisido** [comment] 2022-03-08 13:45
Hi @ragurajesh just saw that this was reopened. Based on the information you supplied, `"timestamp_as_object": True` is the only thing I can think of. If you can provide an example to reproduce this I can look into it

**Closed** 2022-03-23 11:53 UTC
