### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'operation_name'

### ISSUE THREAD

**Issue by londoso** [awslabs/aws-data-wrangler#1510] opened 2022-08-09 01:43 UTC
### Describe the bug

I got this error when trying to execute a query from RdsDataApi.

### How to Reproduce

`import awswrangler as wr

rds = wr.data_api.rds.RdsDataApi(
    resource_arn= 'my_arn', 
    database= 'my_db', 
    secret_arn= 'my_arn_secret'
)

rds.execute('select * from pg_tables;')
`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [146], in <cell line: 1>()
----> 1 rds.execute('select * from pg_tables;')

File /opt/conda/envs/myenv/lib/python3.9/site-packages/awswrangler/data_api/connector.py:27, in DataApiConnector.execute(self, sql, database)
     15 def execute(self, sql: str, database: Optional[str] = None) -> pd.DataFrame:
     16     """Execute SQL statement against a Data API Service.
     17 
     18     Parameters
   (...)
     25     A Pandas DataFrame containing the execution results.
     26     """
---> 27     request_id: str = self._execute_statement(sql, database=database)
     28     return self._get_statement_result(request_id)

File /opt/conda/envs/myenv/lib/python3.9/site-packages/awswrangler/data_api/rds.py:91, in RdsDataApi._execute_statement(self, sql, database)
     89 if response is None:
     90     self.logger.exception("Maximum BadRequestException retries reached for query %s", sql)
---> 91     raise self.client.exceptions.BadRequestException(
     92         f"Query failed - BadRequestException received after {total_tries} tries and sleeping {total_sleep}s"
     93     ) from last_exception
     95 request_id: str = uuid.uuid4().hex
     96 self.results[request_id] = response

TypeError: __init__() missing 1 required positional argument: 'operation_name'

### OS

na

### Python version

3.9.12

### AWS DataWrangler version

2.16.1

### Additional context

Using:
- Sagemaker Studio
- Custom image (conda environment - Python 3.9.12)

**Comment by jaidisido** [comment] 2022-08-09 09:38
Duplicate of https://github.com/awslabs/aws-data-wrangler/issues/1454

**Closed by jaidisido** 2022-08-09 09:38 UTC
Labels: bug

**Comment by jaidisido** [comment] 2022-08-09 16:49
It should be the same root cause since your error trace ends up at the same point (L91 of rds.py). Can you try to install from source as suggested: https://github.com/awslabs/aws-data-wrangler/issues/1454#issuecomment-1189235301

Hopefully that fix should not obfuscate the exception and you can then debug the actual error

**Comment by londoso** [comment] 2022-08-09 17:05
Actually, I installed from the source as indicated in that comment and I got this error.

**Comment by jaidisido** [comment] 2022-08-09 17:12
Are you sure that you installed from source correctly? As you can see, the latest [code](https://github.com/awslabs/aws-data-wrangler/blob/7917504e056c63aa07a337065143d9994cc59b53/awswrangler/data_api/rds.py#L91) does not even have the `BadRequestException` that you raised originally in the issue. From source, it should raise something else. Perhaps you can make sure to uninstall first or install in a separate virtual environment altogether?
